### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/dev--LTSP#13]
- [ ] Install of LTSP in Ubuntu with Vagrant, according to the instructions here: http://dashohoxha.fs.al/ltsp-pnp/ This should be finished by the end of the next week (May 26).
- [ ] Install LTSP in Debian with Vagrant. This should be finished by June 2.
- [ ] Build a Debian package for ltsp-manager. This should be finished by June 9. First evaluation.
- [ ] Port ubuntu-edu packages to Debian. Two weeks. Finish it by June 23.
- [ ] Improve ltsp-manager so that LTSP server can support Raspberry Pi clients. Two weeks. Finish it by July 7. Second Evaluation.
- [ ] Some other small improvements to ltsp-manager that I will detail later. Finish it by July 14.
- [ ] One week to get familiar with docker-scripts. Finished by July 21.
- [ ] Two weeks to build a LTSP server container with docker-scripts. Finished by August 4.
- [ ] One week as a buffer week. Can also be used to complete any docs that was not finished properly along the way.
